import React ,{useState}from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header/header'
import Footer from '../../components/footer/footer'
import ShowOrHideLayout from '../../components/layouts/show_hide_layout'
import WrapListLayout from '../../components/layouts/wrap_list_layout'
import Agenda from '../../components/others/agenda'
import Axios from 'axios'

export default function recruteur() {

    const [company_name,setCompanyName]=useState(false);
    const [company_nationality, setCompanyNationality]=useState(false);
    const [company_representative_status, setCompanyRepresentativeStatus]=useState(false);
    const [company_rcs, setCompanyRcs]=useState(false);
    const [company_headquarters, setCompanyHeadquarters]=useState(false);
    const [company_zip_code, setCompanyZipCode]=useState(false);
    const [company_address, setCompanyAddress]=useState(false);
    const [company_department, setCompanyDepartment]=useState(false);
    const [company_phone_number, setCompanyPhoneNumber]=useState(false);
    const [company_city, setCompanyCity]=useState(false);
    const [company_country, setCompanyCountry]=useState(false);
    const [is_partner, setIsPartner]=useState(0);
    const [partner_type, setPartnerType]=useState('no');
    const [consultant_id, setConsultantId]=useState(5);
    const [company_representative_id, setCompanyRepresentative]=useState(25);

    const register_todo = "A TERMINER";
    
    //Ancre 
    const [show_hide, setShow_hide] =useState(false);
    
    const finalization = (e)=>{
        e.preventDefault()
        if(!company_name || !company_nationality || !company_phone_number || !company_headquarters || !company_address || !company_department || !company_city
            || !company_rcs || !company_zip_code || !company_country || !company_representative_status){

            setAlert(" Veuillez remplir tous les champs pour vous inscrire")

        }else{

           Axios.post('http://localhost:3080/createCompany',{
                
                company_name:company_name,
                company_nationality:company_nationality,
                company_representative_status:company_representative_status,
                company_rcs:company_rcs,
                company_address:company_address,
                company_department:company_department,
                company_phone_number:company_phone_number,
                company_headquarters:company_headquarters,
                company_zip_code:company_zip_code,
                company_city:company_city,
                company_country:company_country,
                company_representative_id:company_representative_id,
                is_partner:is_partner,
                partner_type:partner_type,
                consultant_id:consultant_id

            }).then((resutlt)=>{
                
                if(!resutlt.data.err){
                    window.location.href = `../interface/recruteur`
                }else {
                     setAlert("Deja inscrit")
                }
            });
            console.log(finalization);
        }
    }

    return (
        <div className="interface-layout">
            <Head>
                <title>A recruit | Recruteur</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*---------------*/}
            <Header/>
            {/*---------------*/}
            
            <main className="body">
                   

                <ShowOrHideLayout
                    title = "TERMINER L'INSCRIPTION DE MON ENTREPRISE"
                    statut = {register_todo}
                >
                    <div className="register_todo_container">
                        <div className="underline register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Nom de l'entreprise :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyName(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Nationalité de l'entreprise :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyNationality(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Qualité du signataire :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyRepresentativeStatus(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>RCS + Ville :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyRcs(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Tel :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyPhoneNumber(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Siège social :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyHeadquarters(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Département :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyDepartment(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Code postal :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyZipCode(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Ville :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyCity(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Adresse :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyAddress(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div>
                        <div className="register_todo w100 orientationH spaceBetween center">
                            <div className="orientationH center">
                                <label>Pays :</label><input type="text" name="ent_name" required onChange={(e)=>{setCompanyCountry(e.target.value)}}/>
                            </div>
                            <div className="status">f</div>
                        </div> 
                        <div className="orientationH spaceBetween fromRight "><div className="button full mbem" onClick={(e)=>{finalization(e)}}>VALIDER</div></div>
                    </div>
                </ShowOrHideLayout>
                

                {/* ZONE FAIRE MA DEMANDE */}
                <div className="show_hide_layout orientationH spaceBetween center demandes_link">
                    <div className="orientationH center"><label className="label">FAIRE MA DEMANDE</label></div>
                    <div className="orientationH ">
                        <Link href="#new_demande">
                            <a onClick={()=>setShow_hide(true)}> <div className="button full">DEMANDE EN LIGNE</div></a>
                        </Link>
                        <Link href="">
                            <a> <div className="button full">PRENDRE RENDEZ-VOUS AVEC UN CONSEILLER</div></a>
                        </Link>
                    </div>

                </div>

                {/* DEMANDE EN COURS */}
                <WrapListLayout
                    title= "DEMANDES EN COURS ..............."
                    linkForMore=""
                >
                    <div className="demande">
                        <label>CONSULTANT EN RECRUTEMENT</label>
                        <div>27/09/2021</div>
                        <div>RECRUTÉ : ............</div>
                    </div>
                </WrapListLayout>
                

                {/*MES DEMANDE*/}
                <WrapListLayout
                    title= "DERNIÈRES DEMANDES "
                    linkForMore=""
                >
                    <div className="demande">
                        <label>CONSULTANT EN RECRUTEMENT</label>
                        <div>27/09/2021</div>
                        <div>RECRUTÉ : Albert ANSHTINE</div>
                    </div>
                        
                    <div className="more orientationV center">
                        <Link  href="#new_demande">
                            <a className="center orientationV" onClick={()=>setShow_hide(true)} >
                                <div className="more_btn center">+</div>
                                Ajouter un poste
                            </a>
                        </Link>
                    </div>
                </WrapListLayout>
                
                {/* NOUVELLE DEMANDE FORMULAIRE */}
                <ShowOrHideLayout
                    title = "NOUVELLE OFFRE D'EMPLOIE"
                    show_hide = {show_hide}
                    callback = {()=>setShow_hide(false)}
                >
                    <div id="new_demande">
                        <div className="new_demande underline orientationH spaceBetween w100">
                            {/* CHAMPS DU FORMULAIRE */}
                            <div className="form_new_post orientationV">
                                <br></br>
                                <div className=" register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Intitule du poste :</label><input type="text" name="ent_name"/>
                                    </div>
                                </div>

                                <div className="register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Pays :</label>
                                        <select className="form_select">
                                            <option>--Pays--</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Departement :</label>
                                        <select className="form_select">
                                            <option>--Departement--</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Diplôme requis :</label>
                                        <select className="form_select">
                                            <option>--Choix--</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Niveau d'étude requis :</label>
                                        <select className="form_select">
                                            <option>--Choix--</option>
                                        </select>
                                    </div>
                                </div>
                                <div className="register_todo w100 orientationH spaceBetween center">
                                    <div className="orientationH center">
                                        <label>Expérience requise :</label>
                                        <select className="form_select">
                                            <option>--Choix--</option>
                                        </select>
                                    </div>
                                </div>
                            
                            </div>
                            {/* CHAMPS DU FICHIERS */}
                            <div className="orientationV">
                                <br></br>
                                <div className=" files w100 orientationV spaceBetween ">
                                    <label>Fiche de poste :</label>
                                    <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                </div>

                                <div className=" files w100 orientationV spaceBetween ">
                                    <label>Présentation du poste en pdf:</label>
                                    <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                </div>
                                
                                <div className=" files w100 orientationV spaceBetween ">
                                    <label>Présentation du poste en video :</label>
                                    <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                </div>

                                <div className=" files w100 orientationV spaceBetween ">
                                    <label>Présentation de l'entreprise en pdf :</label>
                                    <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                </div>

                                <div className=" files w100 orientationV spaceBetween ">
                                    <label>Présentation de l'entreprise en video :</label>
                                    <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                </div>

                            </div>

                            {/* CALENDRIER */}
                            <div className="calendrier orientationV">
                                <br></br>
                                <div>Merci de choisir un créneau de RDV afin de finaliser votre demande</div>

                                <Agenda/>
                            </div>

                        </div>
                        <div className="orientationH spaceBetween fromRight "><div className="button full mbem">VALIDER</div></div>

                    </div>

                </ShowOrHideLayout>
                   

                
            </main>

            {/*---------------*/}
            <Footer/>

        </div>
    )
}