import React ,{useState}from 'react'
import Head from 'next/head'
import Header from '../../components/header/header'
import Show_hide_layout from '../../components/users_components/show_hide_layout'
import Footer from '../../components/footer/footer'
import Agenda from '../../components/users_components/agenda'
import Link from 'next/link'

export default function recruteure() {

    const register_todo = "A TERMINER";
    
    //Ancre 
    const [show_hide, setShow_hide] =useState(false);

    return (
        <div className="interface-layout">
            <Head>
                <title>A recruit | Recruteur</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*---------------*/}
            <Header/>
            {/*---------------*/}
            
            <main>
                
                <body className="body">

                    <Show_hide_layout
                        title = "TERMINER L'INSCRIPTION DE MON ENTREPRISE"
                        statut = {register_todo}
                    >
                        <div className="register_todo_container">
                            <div className="underline register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Nom de l'entreprise :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>

                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Qualité du signataire :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>RCS + Ville :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Tel :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Mail :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Siège social :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Code postal :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Ville :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div>
                            <div className="register_todo w100 orientationH spaceBetween center">
                                <div className="orientationH center">
                                    <label>Pays :</label><input type="text" name="ent_name"/>
                                </div>
                                <div className="status">f</div>
                            </div> 
                            <div className="orientationH spaceBetween fromRight "><div className="button full mbem">VALIDER</div></div>
                        </div>

                    </Show_hide_layout>
                   

                    {/* ZONE FAIRE MA DEMANDE */}
                    <div className="show_hide_layout orientationH spaceBetween center demandes_link">
                        <div className="orientationH center"><label className="label">FAIRE MA DEMANDE</label></div>
                        <div className="orientationH ">
                            <Link href="#new_demande">
                                <a onClick={()=>setShow_hide(true)}> <div className="button full">DEMANDE EN LIGNE</div></a>
                            </Link>
                            <Link href="/">
                                <a> <div className="button full">PRENDRE RENDEZ-VOUS AVEC UN CONSEILLER</div></a>
                            </Link>
                        </div>

                    </div>

                    {/* DEMANDE EN COURS */}
                    <div className="show_hide_layout orientationV spaceBetween">
                        <div className="demandes_head">EN COURS .............</div>
                        <div className="demande_list w100 orientationH spaceBetween wrap">
                            <div className="demande">
                                <label>CONSULTANT EN RECRUTEMENT</label>
                                <div>27/09/2021</div>
                                <div>RECRUTÉ : ............</div>
                            </div>
                        </div>
                        <div className="w100 orientationH fromRight">
                            <Link href="/"><a>voir plus »</a></Link>
                        </div>
                    </div>

                    {/*MES DEMANDE*/}
                    <div className="demandes show_hide_layout orientationV spaceBetween">
                        <div className="demandes_head">RECEMMENTS DÉPOSÉ</div>
                        <div className="demande_list w100 orientationH  wrap">
                            <div className="demande">
                                <label>CONSULTANT EN RECRUTEMENT</label>
                                <div>27/09/2021</div>
                                <div>RECRUTÉ : ............</div>
                            </div>
                            
                            <div className="more orientationV center">
                                <Link  href="#new_demande">
                                    <a className="center orientationV" onClick={()=>setShow_hide(true)} >
                                        <div className="more_btn center">+</div>
                                        Ajouter un poste
                                    </a>
                                </Link>
                            </div>
                        </div>
                        <div className="w100 orientationH fromRight">
                            <Link href="/"><a>voir plus »</a></Link>
                        </div>
                    </div>

                    {/* NOUVELLE DEMANDE FORMULAIRE */}
                    <Show_hide_layout
                        title = "NOUVELLE OFFRE D'EMPLOIE"
                        show_hide = {show_hide}
                        callback = {()=>setShow_hide(false)}
                    >
                        <div id="new_demande">
                            <div className="new_demande underline orientationH spaceBetween w100">
                                {/* CHAMPS DU FORMULAIRE */}
                                <div className="form_new_post orientationV">
                                    <br></br>
                                    <div className=" register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Intitule du poste :</label><input type="text" name="ent_name"/>
                                        </div>
                                    </div>

                                    <div className="register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Pays :</label>
                                            <select className="form_select">
                                                <option>--Pays--</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div className="register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Departement :</label>
                                            <select className="form_select">
                                                <option>--Departement--</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div className="register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Diplôme requis :</label>
                                            <select className="form_select">
                                                <option>--Choix--</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div className="register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Niveau d'étude requis :</label>
                                            <select className="form_select">
                                                <option>--Choix--</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div className="register_todo w100 orientationH spaceBetween center">
                                        <div className="orientationH center">
                                            <label>Expérience requise :</label>
                                            <select className="form_select">
                                                <option>--Choix--</option>
                                            </select>
                                        </div>
                                    </div>
                                
                                </div>
                               {/* CHAMPS DU FICHIERS */}
                               <div className="orientationV">
                                    <br></br>
                                    <div className=" files w100 orientationV spaceBetween ">
                                        <label>Fiche de poste :</label>
                                        <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                    </div>

                                    <div className=" files w100 orientationV spaceBetween ">
                                        <label>Présentation du poste en pdf:</label>
                                        <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                    </div>
                                    
                                    <div className=" files w100 orientationV spaceBetween ">
                                        <label>Présentation du poste en video :</label>
                                        <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                    </div>

                                    <div className=" files w100 orientationV spaceBetween ">
                                        <label>Présentation de l'entreprise en pdf :</label>
                                        <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                    </div>

                                    <div className=" files w100 orientationV spaceBetween ">
                                        <label>Présentation de l'entreprise en video :</label>
                                        <input type="file"  name="avatar" accept="image/png, image/jpeg"/>
                                    </div>

                                </div>

                                {/* CALENDRIER */}
                                <div className="calendrier orientationV">
                                    <br></br>
                                    <div>Merci de choisir un créneau de RDV afin de finaliser votre demande</div>

                                    <Agenda/>
                                </div>

                            </div>
                            <div className="orientationH spaceBetween fromRight "><div className="button full mbem">VALIDER</div></div>

                        </div>

                    </Show_hide_layout>
                   

                </body>
                
            </main>

            {/*---------------*/}
            <Footer/>

        </div>
    )
}
